# Generated by Django 5.2.11 on 2026-02-08 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="track",
            name="lyrics",
            field=models.TextField(
                blank=True, help_text="Song lyrics or spoken word text"
            ),
        ),
    ]
