# Generated by Django 5.2.11 on 2026-02-08 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracks", "0002_add_lyrics_to_track"),
    ]

    operations = [
        migrations.AddField(
            model_name="track",
            name="artist_name",
            field=models.CharField(
                blank=True, help_text="AI artist persona name", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="track",
            name="language",
            field=models.CharField(
                blank=True, default="English", help_text="Track language", max_length=20
            ),
        ),
    ]
