# Generated by Django 5.2.11 on 2026-02-09 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracks", "0003_add_artist_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="track",
            name="audio_file",
            field=models.FileField(blank=True, upload_to="tracks/%Y/%m/"),
        ),
    ]
