'use client';

import Link from 'next/link';

const GENRES = [
  'Pop', 'Rock', 'Hip-Hop', 'Electronic', 'Jazz', 'Classical',
  'Ambient', 'Acoustic', 'Lo-Fi', 'Cinematic', 'R&B', 'World',
];

export default function LandingPage() {
  return (
    <div className="mx-auto max-w-6xl px-4 sm:px-6">
      {/* Hero */}
      <section className="flex flex-col items-center pb-16 pt-20 text-center sm:pt-28">
        <div className="mb-6 inline-flex items-center gap-2 rounded-full border border-zinc-800 bg-zinc-900/80 px-4 py-1.5 text-xs text-zinc-400">
          <span className="inline-block h-1.5 w-1.5 rounded-full bg-green-400" />
          100% Free &amp; Royalty-Free
        </div>
        <h1 className="text-4xl font-bold tracking-tight sm:text-5xl lg:text-6xl">
          Discover{' '}
          <span className="bg-gradient-to-r from-violet-400 via-fuchsia-400 to-pink-400 bg-clip-text text-transparent">
            AI-Generated
          </span>
          <br />
          Music Library
        </h1>
        <p className="mx-auto mt-5 max-w-lg text-base text-zinc-400 sm:text-lg">
          Download free, royalty-free music for your videos, podcasts, and
          creative projects. No attribution required.
        </p>
        <div className="mt-8 flex flex-col gap-3 sm:flex-row">
          <Link
            href="/register"
            className="rounded-xl bg-gradient-to-r from-violet-600 to-fuchsia-600 px-8 py-3 text-sm font-semibold text-white shadow-lg shadow-violet-500/20 transition hover:shadow-violet-500/40"
          >
            Sign Up Free
          </Link>
          <Link
            href="/?browse=true"
            className="rounded-xl border border-zinc-700 px-8 py-3 text-sm font-medium text-zinc-300 transition hover:border-zinc-500 hover:text-white"
          >
            Browse Music
          </Link>
        </div>
      </section>

      {/* Features */}
      <section className="grid gap-4 pb-16 sm:grid-cols-3">
        {[
          {
            icon: (
              <svg className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M9 9l10.5-3m0 6.553v3.75a2.25 2.25 0 01-1.632 2.163l-1.32.377a1.803 1.803 0 11-.99-3.467l2.31-.66a2.25 2.25 0 001.632-2.163zm0 0V2.25L9 5.25v10.303m0 0v3.75a2.25 2.25 0 01-1.632 2.163l-1.32.377a1.803 1.803 0 01-.99-3.467l2.31-.66A2.25 2.25 0 009 15.553z" />
              </svg>
            ),
            title: 'AI-Crafted Tracks',
            desc: 'Unique music generated by AI across 14 genres and moods.',
          },
          {
            icon: (
              <svg className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M3 16.5v2.25A2.25 2.25 0 005.25 21h13.5A2.25 2.25 0 0021 18.75V16.5M16.5 12L12 16.5m0 0L7.5 12m4.5 4.5V3" />
              </svg>
            ),
            title: 'Free Downloads',
            desc: 'Download any track instantly. No sign-up walls or hidden fees.',
          },
          {
            icon: (
              <svg className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M9 12.75L11.25 15 15 9.75m-3-7.036A11.959 11.959 0 013.598 6 11.99 11.99 0 003 9.749c0 5.592 3.824 10.29 9 11.623 5.176-1.332 9-6.03 9-11.622 0-1.31-.21-2.571-.598-3.751h-.152c-3.196 0-6.1-1.248-8.25-3.285z" />
              </svg>
            ),
            title: 'No Attribution',
            desc: 'Use in commercial projects freely. No credit required.',
          },
        ].map((f) => (
          <div
            key={f.title}
            className="rounded-2xl border border-zinc-800/60 bg-zinc-900/40 p-6"
          >
            <div className="mb-3 text-violet-400">{f.icon}</div>
            <h3 className="mb-1 text-sm font-semibold text-white">{f.title}</h3>
            <p className="text-sm text-zinc-500">{f.desc}</p>
          </div>
        ))}
      </section>

      {/* Genres */}
      <section className="pb-20 text-center">
        <h2 className="mb-1 text-xs font-semibold uppercase tracking-widest text-zinc-500">
          Genres
        </h2>
        <div className="mt-4 flex flex-wrap justify-center gap-2">
          {GENRES.map((g) => (
            <span
              key={g}
              className="rounded-full border border-zinc-800 bg-zinc-900/60 px-4 py-1.5 text-xs text-zinc-400"
            >
              {g}
            </span>
          ))}
        </div>
      </section>
    </div>
  );
}
