GENRE_TEMPLATES = {
    "lofi": {
        "bpm_range": (70, 90),
        "scales": ["minor", "dorian"],
        "root_range": (55, 62),  # MIDI: G3 to D4
        "chord_osc": "triangle",
        "bass_osc": "sine",
        "melody_osc": "sine",
        "pad_osc": "triangle",
        "drum_patterns": {
            "K": "x---x---x---x---",
            "S": "----x-------x---",
            "H": "x-x-x-x-x-x-x-x",
        },
        "swing": 0.3,
        "volumes": {"chords": 0.25, "bass": 0.30, "drums": 0.25, "melody": 0.20, "pad": 0.10},
        "effects": {"chords": [("low_pass", 800)], "melody": [("low_pass", 2000)], "master": [("reverb", 0.3)]},
        "melody_rest_prob": 0.3,
    },
    "electronic": {
        "bpm_range": (120, 135),
        "scales": ["minor"],
        "root_range": (48, 58),
        "chord_osc": "saw",
        "bass_osc": "saw",
        "melody_osc": "saw",
        "pad_osc": "sine",
        "drum_patterns": {
            "K": "x---x---x---x---",
            "S": "----x-------x---",
            "H": "x-x-x-x-x-x-x-x",
            "O": "--------x-------",
        },
        "swing": 0.0,
        "volumes": {"chords": 0.20, "bass": 0.30, "drums": 0.30, "melody": 0.20, "pad": 0.08},
        "effects": {"chords": [("low_pass", 2000)], "bass": [("low_pass", 500)], "master": [("reverb", 0.15)]},
        "melody_rest_prob": 0.15,
    },
    "ambient": {
        "bpm_range": (50, 70),
        "scales": ["major", "whole_tone"],
        "root_range": (48, 60),
        "chord_osc": "sine",
        "bass_osc": "sine",
        "melody_osc": "triangle",
        "pad_osc": "sine",
        "drum_patterns": {},
        "swing": 0.0,
        "volumes": {"chords": 0.20, "bass": 0.15, "drums": 0.0, "melody": 0.15, "pad": 0.35},
        "effects": {"pad": [("low_pass", 600), ("reverb", 0.5)], "melody": [("reverb", 0.4)], "master": [("reverb", 0.4)]},
        "melody_rest_prob": 0.5,
    },
    "hiphop": {
        "bpm_range": (85, 100),
        "scales": ["minor", "blues"],
        "root_range": (40, 52),
        "chord_osc": "triangle",
        "bass_osc": "sine",
        "melody_osc": "triangle",
        "pad_osc": "sine",
        "drum_patterns": {
            "K": "x--x--x---x-x---",
            "S": "----x-------x---",
            "H": "x-xxx-xxx-xxx-xx",
            "C": "----x-------x---",
        },
        "swing": 0.1,
        "volumes": {"chords": 0.20, "bass": 0.35, "drums": 0.30, "melody": 0.15, "pad": 0.05},
        "effects": {"bass": [("low_pass", 300)], "master": [("reverb", 0.1)]},
        "melody_rest_prob": 0.35,
    },
    "jazz": {
        "bpm_range": (80, 140),
        "scales": ["dorian", "mixolydian"],
        "root_range": (48, 62),
        "chord_osc": "sine",
        "bass_osc": "sine",
        "melody_osc": "sine",
        "pad_osc": "triangle",
        "drum_patterns": {
            "K": "x-------x-------",
            "S": "----x-------x---",
            "H": "x-xx-xx-x-xx-xx-",
        },
        "swing": 0.4,
        "volumes": {"chords": 0.25, "bass": 0.30, "drums": 0.20, "melody": 0.25, "pad": 0.0},
        "effects": {"master": [("reverb", 0.25)]},
        "melody_rest_prob": 0.15,
    },
    "rock": {
        "bpm_range": (110, 145),
        "scales": ["major", "mixolydian"],
        "root_range": (40, 52),
        "chord_osc": "saw",
        "bass_osc": "saw",
        "melody_osc": "square",
        "pad_osc": None,
        "drum_patterns": {
            "K": "x---x---x---x---",
            "S": "----x-------x---",
            "H": "x-x-x-x-x-x-x-x",
            "C": "--------x-------",
        },
        "swing": 0.0,
        "volumes": {"chords": 0.30, "bass": 0.30, "drums": 0.30, "melody": 0.15, "pad": 0.0},
        "effects": {"chords": [("distortion", 3.0)], "bass": [("distortion", 1.5)], "master": [("reverb", 0.15)]},
        "melody_rest_prob": 0.2,
    },
    "acoustic": {
        "bpm_range": (80, 115),
        "scales": ["major"],
        "root_range": (48, 62),
        "chord_osc": "triangle",
        "bass_osc": "triangle",
        "melody_osc": "triangle",
        "pad_osc": None,
        "drum_patterns": {
            "K": "x-------x-------",
            "S": "----x-------x---",
            "H": "x---x---x---x---",
        },
        "swing": 0.05,
        "volumes": {"chords": 0.30, "bass": 0.25, "drums": 0.15, "melody": 0.25, "pad": 0.0},
        "effects": {"master": [("reverb", 0.2)]},
        "melody_rest_prob": 0.2,
    },
    "chiptune": {
        "bpm_range": (120, 160),
        "scales": ["major", "minor"],
        "root_range": (48, 65),
        "chord_osc": "pulse",
        "bass_osc": "square",
        "melody_osc": "pulse",
        "pad_osc": None,
        "drum_patterns": {
            "K": "x---x---x---x---",
            "S": "----x-------x---",
            "H": "x-x-x-x-x-x-x-x",
        },
        "swing": 0.0,
        "volumes": {"chords": 0.25, "bass": 0.25, "drums": 0.25, "melody": 0.30, "pad": 0.0},
        "effects": {"chords": [("bitcrush", 6)], "melody": [("bitcrush", 6)], "bass": [("bitcrush", 8)]},
        "melody_rest_prob": 0.1,
    },
}

GENRE_ALIASES = {
    "pop": "electronic",
    "classical": "ambient",
    "cinematic": "ambient",
    "r&b": "lofi",
    "rnb": "lofi",
    "soul": "jazz",
    "funk": "jazz",
    "metal": "rock",
    "punk": "rock",
    "country": "acoustic",
    "folk": "acoustic",
    "reggae": "acoustic",
    "trap": "hiphop",
    "drill": "hiphop",
    "edm": "electronic",
    "house": "electronic",
    "techno": "electronic",
    "trance": "electronic",
    "dubstep": "electronic",
    "synthwave": "electronic",
    "vaporwave": "lofi",
    "indie": "acoustic",
    "blues": "jazz",
    "latin": "acoustic",
    "world": "acoustic",
    "retro": "chiptune",
    "8-bit": "chiptune",
    "8bit": "chiptune",
}


def get_genre_template(genre_name):
    key = genre_name.lower().replace("-", "").replace(" ", "")
    if key in GENRE_TEMPLATES:
        return GENRE_TEMPLATES[key]
    for alias_key, target in GENRE_ALIASES.items():
        if alias_key.replace("-", "").replace(" ", "") == key:
            return GENRE_TEMPLATES[target]
    return GENRE_TEMPLATES["electronic"]
